# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: mpozuelo-MGI_demux-1.0
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  ##conda forge packages
  - conda-forge::python=3.6.10
  - conda-forge::pigz=2.3.4

  ##bioconda packages
  - bioconda::mosdepth=0.2.6
  - bioconda::samtools=1.9

  - pandas=1.2.1
